mode: arduino  # simulation | arduino | replay

baud: 115200
port: "COM4"
#groups for the simulation. If more is needed add it here
groups:
  - name: Distance Sensors
    type: UltraSonicSensor
    sensors:
      - name: sensor 1
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0
      - name: sensor 2
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0
      - name: sensor 3
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0.001
  - name: Distance Sensors1
    type: UltraSonicSensor
    sensors:
      - name: sensor 1
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0
      - name: sensor 2
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0
      - name: sensor 3
        min: 0
        max: 30
        noise: 1
        warning: 20
        failrate: 0.001

replay: logs/system_log.json
